[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.26"

[rpc_endpoints]
sei_testnet = "https://rpc-evm-atlantic-2.seitrace.com"
sei_mainnet = "https://evm-rpc.sei-apis.com"

[etherscan]
sei_testnet = { key = "${SEI_ETHERSCAN_API_KEY}", url = "https://seitrace.com/api" }
sei_mainnet = { key = "${SEI_ETHERSCAN_API_KEY}", url = "https://seitrace.com/api" }