name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  smart-contracts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run Forge build
      run: |
        forge --version
        forge build --sizes

    - name: Run Forge tests
      run: |
        forge test -vvv

  mcp-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: packages/mcp/package-lock.json

    - name: Install dependencies
      run: |
        cd packages/mcp
        npm ci

    - name: Build
      run: |
        cd packages/mcp
        npm run build

    - name: Run tests
      run: |
        cd packages/mcp
        npm test

    - name: Lint
      run: |
        cd packages/mcp
        npm run lint

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: apps/web/package-lock.json

    - name: Install dependencies
      run: |
        cd apps/web
        npm ci

    - name: Build
      run: |
        cd apps/web
        npm run build
      env:
        NEXT_PUBLIC_CHAIN_ID: 1328
        NEXT_PUBLIC_RPC_URL: https://evm-rpc-testnet.sei-apis.com
        NEXT_PUBLIC_FACTORY_ADDRESS: "0xfF0e7F71a0e19E0BF037Bd90Ba30A2Ee409E53a7"
        NEXT_PUBLIC_USDC_ADDRESS: "0x4fCF1784B31630811181f670Aea7A7bEF803eaED"

    - name: Run tests
      run: |
        cd apps/web
        npm test

    - name: Lint
      run: |
        cd apps/web
        npm run lint

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        target: 'contracts/'
        slither-config: 'slither.config.json'
        fail-on: none
        slither-args: '--filter-paths "lib/"'

    - name: Create/update checklist as PR comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        REPORT: ${{ steps.slither.outputs.stdout }}
      with:
        script: |
          const script = require('.github/scripts/comment')
          const header = '## Slither report'
          const body = process.env.REPORT
          await script({ github, context, header, body })

  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [smart-contracts, mcp-server, frontend]
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Vercel Preview
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: apps/web
        scope: ${{ secrets.VERCEL_ORG_ID }}